// This file is partially auto-generated by scripts/generate-course-data.mjs
// Chapter metadata comes from chapter-metadata.ts (single source of truth)
// Lessons are auto-discovered from the file system
// Run: npm run generate-course-data

import { ChapterIconType } from "./chapter-icons"
import { chapterMetadata } from "./chapter-metadata"

export interface Lesson {
  id: string
  title: string
  slug: string
}

export interface Chapter {
  id: string
  number: number
  title: string
  description: string
  icon: ChapterIconType
  lessons: Lesson[]
}

export interface Course {
  id: string
  title: string
  description: string
  chapters: Chapter[]
}

export const courseData: Course = {
  id: "learn-webiny",
  title: "Learn Webiny",
  description:
    "Go from beginner to expert by learning the foundations of Webiny and building a fully functional serverless application that uses all the latest features.",
  chapters: [
    {
        id: "ai-agents-and-mcp-server",
        ...chapterMetadata["ai-agents-and-mcp-server"],
        lessons: [
                  {
                            "id": "built-in-skills",
                            "title": "Built-in Skills",
                            "slug": "ai-agents-and-mcp-server/built-in-skills"
                  },
                  {
                            "id": "installing-the-mcp-server",
                            "title": "Installing the MCP Server",
                            "slug": "ai-agents-and-mcp-server/installing-the-mcp-server"
                  },
                  {
                            "id": "intro",
                            "title": "Building with AI Agents and Webiny MCP Server",
                            "slug": "ai-agents-and-mcp-server/intro"
                  },
                  {
                            "id": "real-world-workflows",
                            "title": "Real-World Workflows",
                            "slug": "ai-agents-and-mcp-server/real-world-workflows"
                  },
                  {
                            "id": "what-is-the-webiny-mcp-server",
                            "title": "What Is the Webiny MCP Server",
                            "slug": "ai-agents-and-mcp-server/what-is-the-webiny-mcp-server"
                  },
                  {
                            "id": "writing-custom-skills",
                            "title": "Writing Your Own Skills",
                            "slug": "ai-agents-and-mcp-server/writing-custom-skills"
                  }
        ]
    },
    {
        id: "developing-with-webiny",
        ...chapterMetadata["developing-with-webiny"],
        lessons: [
                  {
                            "id": "ai-assisted-development",
                            "title": "AI-Assisted Development",
                            "slug": "developing-with-webiny/ai-assisted-development"
                  },
                  {
                            "id": "debugging-errors-best-practices",
                            "title": "Debugging Errors & Best Practices",
                            "slug": "developing-with-webiny/debugging-errors-best-practices"
                  },
                  {
                            "id": "extensions",
                            "title": "Extensions",
                            "slug": "developing-with-webiny/extensions"
                  },
                  {
                            "id": "intro",
                            "title": "Developing with Webiny",
                            "slug": "developing-with-webiny/intro"
                  },
                  {
                            "id": "local-development",
                            "title": "Local Development",
                            "slug": "developing-with-webiny/local-development"
                  },
                  {
                            "id": "project-folder-structure",
                            "title": "Project Folder Structure",
                            "slug": "developing-with-webiny/project-folder-structure"
                  },
                  {
                            "id": "webiny-sdk-overview",
                            "title": "Webiny SDK",
                            "slug": "developing-with-webiny/webiny-sdk-overview"
                  },
                  {
                            "id": "whitelabel-extension",
                            "title": "White-Label Extension",
                            "slug": "developing-with-webiny/whitelabel-extension"
                  }
        ]
    },
    {
        id: "foundation",
        ...chapterMetadata["foundation"],
        lessons: [
                  {
                            "id": "about",
                            "title": "About Webiny",
                            "slug": "foundation/about"
                  },
                  {
                            "id": "infra-and-hosting",
                            "title": "Infrastructure and Hosting",
                            "slug": "foundation/infra-and-hosting"
                  },
                  {
                            "id": "multi-tenancy",
                            "title": "Multi-Tenancy",
                            "slug": "foundation/multi-tenancy"
                  },
                  {
                            "id": "webiny-apps",
                            "title": "Webiny Applications",
                            "slug": "foundation/webiny-apps"
                  },
                  {
                            "id": "webiny-framework",
                            "title": "Webiny Framework",
                            "slug": "foundation/webiny-framework"
                  },
                  {
                            "id": "webiny-parts",
                            "title": "Parts that make Webiny",
                            "slug": "foundation/webiny-parts"
                  }
        ]
    },
    {
        id: "getting-started",
        ...chapterMetadata["getting-started"],
        lessons: [
                  {
                            "id": "deploy-webiny",
                            "title": "Deploy Webiny",
                            "slug": "getting-started/deploy-webiny"
                  },
                  {
                            "id": "installing-webiny",
                            "title": "Installing Webiny",
                            "slug": "getting-started/installing-webiny"
                  },
                  {
                            "id": "webiny-cli-overview",
                            "title": "Webiny CLI Overview",
                            "slug": "getting-started/webiny-cli-overview"
                  }
        ]
    },
    {
        id: "headless-cms",
        ...chapterMetadata["headless-cms"],
        lessons: [
                  {
                            "id": "content-models-and-entries",
                            "title": "Content Models and Content Entries",
                            "slug": "headless-cms/content-models-and-entries"
                  },
                  {
                            "id": "content-versioning",
                            "title": "Content Versioning",
                            "slug": "headless-cms/content-versioning"
                  },
                  {
                            "id": "creating-content-model-via-code",
                            "title": "Creating a Content Model via Code",
                            "slug": "headless-cms/creating-content-model-via-code"
                  },
                  {
                            "id": "creating-content-model-via-ui",
                            "title": "Creating a Content Model via UI",
                            "slug": "headless-cms/creating-content-model-via-ui"
                  },
                  {
                            "id": "customize-data-list",
                            "title": "Customize Data List",
                            "slug": "headless-cms/customize-data-list"
                  },
                  {
                            "id": "learn-webiny-nextjs-app",
                            "title": "Learn Webiny Next.js App",
                            "slug": "headless-cms/learn-webiny-nextjs-app"
                  },
                  {
                            "id": "lifecycle-events",
                            "title": "Lifecycle Events",
                            "slug": "headless-cms/lifecycle-events"
                  },
                  {
                            "id": "reading-data",
                            "title": "Reading Data",
                            "slug": "headless-cms/reading-data"
                  },
                  {
                            "id": "writing-data",
                            "title": "Writing Data",
                            "slug": "headless-cms/writing-data"
                  }
        ]
    },
    {
        id: "website-builder",
        ...chapterMetadata["website-builder"],
        lessons: [
                  {
                            "id": "article-listing-editor-component",
                            "title": "Product Listing Editor Component",
                            "slug": "website-builder/article-listing-editor-component"
                  },
                  {
                            "id": "editor-components",
                            "title": "Editor Components",
                            "slug": "website-builder/editor-components"
                  },
                  {
                            "id": "setting-up-website-builder",
                            "title": "Setting up Website Builder",
                            "slug": "website-builder/setting-up-website-builder"
                  },
                  {
                            "id": "theming-and-styling",
                            "title": "Theming and Styling",
                            "slug": "website-builder/theming-and-styling"
                  }
        ]
    }
],
}

export function getAllLessons(): Array<{ chapterId: string; lessonId: string; slug: string }> {
  const lessons: Array<{ chapterId: string; lessonId: string; slug: string }> = []

  courseData.chapters.forEach((chapter) => {
    chapter.lessons.forEach((lesson) => {
      lessons.push({
        chapterId: chapter.id,
        lessonId: lesson.id,
        slug: lesson.slug,
      })
    })
  })

  return lessons
}

export function getNextLesson(currentSlug: string): { chapterId: string; lessonId: string; slug: string } | null {
  const allLessons = getAllLessons()
  const currentIndex = allLessons.findIndex((l) => l.slug === currentSlug)

  if (currentIndex === -1 || currentIndex === allLessons.length - 1) {
    return null
  }

  return allLessons[currentIndex + 1]
}

export function getPreviousLesson(currentSlug: string): { chapterId: string; lessonId: string; slug: string } | null {
  const allLessons = getAllLessons()
  const currentIndex = allLessons.findIndex((l) => l.slug === currentSlug)

  if (currentIndex <= 0) {
    return null
  }

  return allLessons[currentIndex - 1]
}

export function getLessonBySlug(slug: string) {
  for (const chapter of courseData.chapters) {
    const lesson = chapter.lessons.find((l) => l.slug === slug)
    if (lesson) {
      return { chapter, lesson }
    }
  }
  return null
}

export function isLastLessonInChapter(slug: string): boolean {
  const result = getLessonBySlug(slug)
  if (!result) return false

  const { chapter, lesson } = result
  const lessonIndex = chapter.lessons.findIndex((l) => l.id === lesson.id)
  return lessonIndex === chapter.lessons.length - 1
}

export function getNextChapter(currentSlug: string): Chapter | null {
  const result = getLessonBySlug(currentSlug)
  if (!result) return null

  const { chapter } = result
  const chapterIndex = courseData.chapters.findIndex((c) => c.id === chapter.id)

  if (chapterIndex === -1 || chapterIndex === courseData.chapters.length - 1) {
    return null
  }

  return courseData.chapters[chapterIndex + 1]
}

export function getChapterById(chapterId: string): Chapter | null {
  return courseData.chapters.find((c) => c.id === chapterId) || null
}

export function getLessonNumber(slug: string): number {
  const allLessons = getAllLessons()
  const index = allLessons.findIndex((l) => l.slug === slug)
  return index !== -1 ? index + 1 : 0
}

export function getLessonNumberInChapter(slug: string): number {
  const result = getLessonBySlug(slug)
  if (!result) return 0

  const { chapter, lesson } = result
  const lessonIndex = chapter.lessons.findIndex((l) => l.id === lesson.id)
  return lessonIndex !== -1 ? lessonIndex + 1 : 0
}
