// This file is partially auto-generated by scripts/generate-course-data.mjs
// Chapter metadata comes from chapter-metadata.ts (single source of truth)
// Lessons are auto-discovered from the file system
// Run: npm run generate-course-data

import { ChapterIconType } from "./chapter-icons"
import { chapterMetadata } from "./chapter-metadata"

export interface Lesson {
  id: string
  title: string
  slug: string
}

export interface Chapter {
  id: string
  number: number
  title: string
  description: string
  icon: ChapterIconType
  lessons: Lesson[]
}

export interface Course {
  id: string
  title: string
  description: string
  chapters: Chapter[]
}

export const courseData: Course = {
  id: "learn-webiny",
  title: "Learn Webiny",
  description:
    "Go from beginner to expert by learning the foundations of Webiny and building a fully functional serverless application that uses all the latest features.",
  chapters: [
    {
        id: "foundation",
        ...chapterMetadata["foundation"],
        lessons: [
                  {
                            "id": "about",
                            "title": "About Webiny",
                            "slug": "foundation/about"
                  },
                  {
                            "id": "infra-and-hosting",
                            "title": "Infrastructure and Hosting",
                            "slug": "foundation/infra-and-hosting"
                  },
                  {
                            "id": "multi-tenancy",
                            "title": "Multi-Tenancy",
                            "slug": "foundation/multi-tenancy"
                  },
                  {
                            "id": "webiny-apps",
                            "title": "Webiny Applications",
                            "slug": "foundation/webiny-apps"
                  },
                  {
                            "id": "webiny-framework",
                            "title": "Webiny Framework",
                            "slug": "foundation/webiny-framework"
                  },
                  {
                            "id": "webiny-parts",
                            "title": "Parts that make Webiny",
                            "slug": "foundation/webiny-parts"
                  }
        ]
    },
    {
        id: "getting-started",
        ...chapterMetadata["getting-started"],
        lessons: [
                  {
                            "id": "installing-webiny",
                            "title": "Installing Webiny",
                            "slug": "getting-started/installing-webiny"
                  },
                  {
                            "id": "webiny-cli-overview",
                            "title": "Webiny CLI Overview",
                            "slug": "getting-started/webiny-cli-overview"
                  },
                  {
                            "id": "webiny-deployments",
                            "title": "Deployment Environments",
                            "slug": "getting-started/webiny-deployments"
                  }
        ]
    }
],
}

export function getAllLessons(): Array<{ chapterId: string; lessonId: string; slug: string }> {
  const lessons: Array<{ chapterId: string; lessonId: string; slug: string }> = []

  courseData.chapters.forEach((chapter) => {
    chapter.lessons.forEach((lesson) => {
      lessons.push({
        chapterId: chapter.id,
        lessonId: lesson.id,
        slug: lesson.slug,
      })
    })
  })

  return lessons
}

export function getNextLesson(currentSlug: string): { chapterId: string; lessonId: string; slug: string } | null {
  const allLessons = getAllLessons()
  const currentIndex = allLessons.findIndex((l) => l.slug === currentSlug)

  if (currentIndex === -1 || currentIndex === allLessons.length - 1) {
    return null
  }

  return allLessons[currentIndex + 1]
}

export function getPreviousLesson(currentSlug: string): { chapterId: string; lessonId: string; slug: string } | null {
  const allLessons = getAllLessons()
  const currentIndex = allLessons.findIndex((l) => l.slug === currentSlug)

  if (currentIndex <= 0) {
    return null
  }

  return allLessons[currentIndex - 1]
}

export function getLessonBySlug(slug: string) {
  for (const chapter of courseData.chapters) {
    const lesson = chapter.lessons.find((l) => l.slug === slug)
    if (lesson) {
      return { chapter, lesson }
    }
  }
  return null
}

export function isLastLessonInChapter(slug: string): boolean {
  const result = getLessonBySlug(slug)
  if (!result) return false

  const { chapter, lesson } = result
  const lessonIndex = chapter.lessons.findIndex((l) => l.id === lesson.id)
  return lessonIndex === chapter.lessons.length - 1
}

export function getNextChapter(currentSlug: string): Chapter | null {
  const result = getLessonBySlug(currentSlug)
  if (!result) return null

  const { chapter } = result
  const chapterIndex = courseData.chapters.findIndex((c) => c.id === chapter.id)

  if (chapterIndex === -1 || chapterIndex === courseData.chapters.length - 1) {
    return null
  }

  return courseData.chapters[chapterIndex + 1]
}

export function getChapterById(chapterId: string): Chapter | null {
  return courseData.chapters.find((c) => c.id === chapterId) || null
}

export function getLessonNumber(slug: string): number {
  const allLessons = getAllLessons()
  const index = allLessons.findIndex((l) => l.slug === slug)
  return index !== -1 ? index + 1 : 0
}

export function getLessonNumberInChapter(slug: string): number {
  const result = getLessonBySlug(slug)
  if (!result) return 0

  const { chapter, lesson } = result
  const lessonIndex = chapter.lessons.findIndex((l) => l.id === lesson.id)
  return lessonIndex !== -1 ? lessonIndex + 1 : 0
}
