// Certification Exam Questions
// Each exam should have 20-30 questions

export interface ExamQuestion {
  id: string
  question: string
  type: 'multiple-choice'
  options: string[]
  correctAnswer: number
}

export const examQuestions = {
  associate: [
    {
      id: 'a1',
      question: 'What cloud platform is Webiny primarily built on?',
      type: 'multiple-choice' as const,
      options: ['AWS (Amazon Web Services)', 'Microsoft Azure', 'Google Cloud Platform', 'DigitalOcean'],
      correctAnswer: 0,
    },
    {
      id: 'a2',
      question: 'Which architecture pattern does Webiny use?',
      type: 'multiple-choice' as const,
      options: ['Monolithic', 'Microservices', 'Serverless', 'Event-driven'],
      correctAnswer: 2,
    },
    {
      id: 'a3',
      question: 'What is the primary programming language used in Webiny?',
      type: 'multiple-choice' as const,
      options: ['Python', 'JavaScript/TypeScript', 'Java', 'Go'],
      correctAnswer: 1,
    },
    {
      id: 'a4',
      question: 'Which of the following is NOT a core Webiny application?',
      type: 'multiple-choice' as const,
      options: ['Admin Panel', 'Headless CMS', 'E-commerce Store', 'Page Builder'],
      correctAnswer: 2,
    },
    {
      id: 'a5',
      question: 'What command is used to create a new Webiny project?',
      type: 'multiple-choice' as const,
      options: ['webiny create', 'npx create-webiny-app', 'webiny init', 'npm install webiny'],
      correctAnswer: 1,
    },
    {
      id: 'a6',
      question: 'Which AWS service does Webiny use for compute?',
      type: 'multiple-choice' as const,
      options: ['EC2', 'Lambda', 'ECS', 'Fargate'],
      correctAnswer: 1,
    },
    {
      id: 'a7',
      question: 'What is the purpose of the Admin app in Webiny?',
      type: 'multiple-choice' as const,
      options: ['To manage infrastructure', 'To manage content and settings', 'To deploy applications', 'To monitor performance'],
      correctAnswer: 1,
    },
    {
      id: 'a8',
      question: 'Which database does Webiny use by default?',
      type: 'multiple-choice' as const,
      options: ['MySQL', 'PostgreSQL', 'DynamoDB', 'MongoDB'],
      correctAnswer: 2,
    },
    {
      id: 'a9',
      question: 'What is a key benefit of serverless architecture?',
      type: 'multiple-choice' as const,
      options: ['Fixed monthly costs', 'Manual scaling', 'Pay-per-use pricing', 'Requires server management'],
      correctAnswer: 2,
    },
    {
      id: 'a10',
      question: 'Which tool does Webiny use for infrastructure as code?',
      type: 'multiple-choice' as const,
      options: ['Terraform', 'CloudFormation', 'Pulumi', 'AWS CDK'],
      correctAnswer: 2,
    },
    {
      id: 'a11',
      question: 'What file format is used for content models in Webiny?',
      type: 'multiple-choice' as const,
      options: ['XML', 'JSON', 'YAML', 'TOML'],
      correctAnswer: 1,
    },
    {
      id: 'a12',
      question: 'Which React framework does Webiny use?',
      type: 'multiple-choice' as const,
      options: ['Next.js', 'Gatsby', 'Create React App', 'Custom framework'],
      correctAnswer: 3,
    },
    {
      id: 'a13',
      question: 'What is the purpose of the Page Builder in Webiny?',
      type: 'multiple-choice' as const,
      options: ['To write code', 'To create visual web pages', 'To manage databases', 'To deploy applications'],
      correctAnswer: 1,
    },
    {
      id: 'a14',
      question: 'Which authentication method does Webiny support out of the box?',
      type: 'multiple-choice' as const,
      options: ['OAuth only', 'Cognito', 'Auth0 only', 'Basic authentication'],
      correctAnswer: 1,
    },
    {
      id: 'a15',
      question: 'What is a "headless CMS"?',
      type: 'multiple-choice' as const,
      options: ['A CMS without a database', 'A CMS without a frontend', 'A CMS without users', 'A CMS without content'],
      correctAnswer: 1,
    },
    {
      id: 'a16',
      question: 'How does Webiny handle file storage?',
      type: 'multiple-choice' as const,
      options: ['Local filesystem', 'S3', 'FTP server', 'Database BLOBs'],
      correctAnswer: 1,
    },
    {
      id: 'a17',
      question: 'What is the minimum Node.js version required for Webiny?',
      type: 'multiple-choice' as const,
      options: ['Node.js 12', 'Node.js 14', 'Node.js 16', 'Node.js 18'],
      correctAnswer: 3,
    },
    {
      id: 'a18',
      question: 'Which GraphQL implementation does Webiny use?',
      type: 'multiple-choice' as const,
      options: ['Apollo Server', 'GraphQL Yoga', 'Custom implementation', 'Prisma'],
      correctAnswer: 0,
    },
    {
      id: 'a19',
      question: 'What is the purpose of environments in Webiny?',
      type: 'multiple-choice' as const,
      options: ['To separate dev/staging/prod', 'To manage users', 'To organize content', 'To handle versions'],
      correctAnswer: 0,
    },
    {
      id: 'a20',
      question: 'How are Webiny plugins installed?',
      type: 'multiple-choice' as const,
      options: ['Via AWS Console', 'Via npm packages', 'Via FTP', 'Via database import'],
      correctAnswer: 1,
    },
  ],
  professional: [
    {
      id: 'p1',
      question: 'What is the purpose of Content Model Groups in Webiny?',
      type: 'multiple-choice' as const,
      options: ['To organize related content models', 'To deploy models', 'To backup content', 'To share models between environments'],
      correctAnswer: 0,
    },
    {
      id: 'p2',
      question: 'Which field type allows for rich text editing in Webiny CMS?',
      type: 'multiple-choice' as const,
      options: ['Text', 'Long Text', 'Rich Text', 'HTML'],
      correctAnswer: 2,
    },
    {
      id: 'p3',
      question: 'How do you query content from Webiny Headless CMS?',
      type: 'multiple-choice' as const,
      options: ['REST API', 'GraphQL API', 'SQL queries', 'FTP'],
      correctAnswer: 1,
    },
    {
      id: 'p4',
      question: 'What is a Page Builder element in Webiny?',
      type: 'multiple-choice' as const,
      options: ['A database table', 'A reusable UI component', 'A deployment script', 'A user role'],
      correctAnswer: 1,
    },
    {
      id: 'p5',
      question: 'How can you extend Webiny functionality?',
      type: 'multiple-choice' as const,
      options: ['Editing core files', 'Creating plugins', 'Direct database access', 'Using FTP'],
      correctAnswer: 1,
    },
    {
      id: 'p6',
      question: 'What is the purpose of API Keys in Webiny?',
      type: 'multiple-choice' as const,
      options: ['To access AWS Console', 'To authenticate API requests', 'To deploy applications', 'To backup data'],
      correctAnswer: 1,
    },
    {
      id: 'p7',
      question: 'Which command deploys a Webiny project?',
      type: 'multiple-choice' as const,
      options: ['yarn deploy', 'npm run deploy', 'webiny deploy', 'aws deploy'],
      correctAnswer: 0,
    },
    {
      id: 'p8',
      question: 'What is content localization in Webiny?',
      type: 'multiple-choice' as const,
      options: ['Organizing content by location', 'Multi-language content support', 'Content versioning', 'Content backup'],
      correctAnswer: 1,
    },
    {
      id: 'p9',
      question: 'How does Webiny handle content versioning?',
      type: 'multiple-choice' as const,
      options: ['Manual backups', 'Git integration', 'Built-in revision system', 'No versioning'],
      correctAnswer: 2,
    },
    {
      id: 'p10',
      question: 'What is the purpose of Content Entry Lifecycle Hooks?',
      type: 'multiple-choice' as const,
      options: ['To delete old content', 'To run custom logic on content events', 'To backup content', 'To translate content'],
      correctAnswer: 1,
    },
    {
      id: 'p11',
      question: 'Which AWS service does Webiny use for API Gateway?',
      type: 'multiple-choice' as const,
      options: ['API Gateway', 'CloudFront', 'Route 53', 'ALB'],
      correctAnswer: 0,
    },
    {
      id: 'p12',
      question: 'How do you create custom GraphQL resolvers in Webiny?',
      type: 'multiple-choice' as const,
      options: ['Editing database directly', 'Through plugins', 'Via Admin UI', 'Using SQL'],
      correctAnswer: 1,
    },
    {
      id: 'p13',
      question: 'What is the purpose of the Security Framework in Webiny?',
      type: 'multiple-choice' as const,
      options: ['Database encryption', 'User authentication and authorization', 'Network security', 'Code obfuscation'],
      correctAnswer: 1,
    },
    {
      id: 'p14',
      question: 'How are assets optimized in Webiny?',
      type: 'multiple-choice' as const,
      options: ['Manual compression', 'CloudFront CDN', 'Local caching', 'No optimization'],
      correctAnswer: 1,
    },
    {
      id: 'p15',
      question: 'What is the purpose of Environment Variables in Webiny?',
      type: 'multiple-choice' as const,
      options: ['To store secrets and configuration', 'To deploy code', 'To backup data', 'To manage users'],
      correctAnswer: 0,
    },
    {
      id: 'p16',
      question: 'How do you implement custom page elements?',
      type: 'multiple-choice' as const,
      options: ['Editing core files', 'Creating React components and plugins', 'Using SQL', 'FTP upload'],
      correctAnswer: 1,
    },
    {
      id: 'p17',
      question: 'What is the purpose of the File Manager in Webiny?',
      type: 'multiple-choice' as const,
      options: ['To manage source code', 'To manage media assets', 'To manage databases', 'To manage servers'],
      correctAnswer: 1,
    },
    {
      id: 'p18',
      question: 'How does Webiny handle form submissions?',
      type: 'multiple-choice' as const,
      options: ['Email only', 'Stored in DynamoDB', 'Not supported', 'FTP upload'],
      correctAnswer: 1,
    },
    {
      id: 'p19',
      question: 'What is the purpose of Webiny CLI?',
      type: 'multiple-choice' as const,
      options: ['To browse websites', 'To manage and deploy Webiny projects', 'To edit databases', 'To monitor servers'],
      correctAnswer: 1,
    },
    {
      id: 'p20',
      question: 'How do you implement multi-tenancy in Webiny?',
      type: 'multiple-choice' as const,
      options: ['Separate databases', 'Tenant isolation features', 'Not supported', 'Manual configuration'],
      correctAnswer: 1,
    },
  ],
  expert: [
    {
      id: 'e1',
      question: 'What is the recommended approach for custom business logic in Webiny?',
      type: 'multiple-choice' as const,
      options: ['Modifying core code', 'Creating custom plugins', 'Direct database access', 'Using Lambda functions only'],
      correctAnswer: 1,
    },
    {
      id: 'e2',
      question: 'How should you implement caching in a Webiny application?',
      type: 'multiple-choice' as const,
      options: ['Browser cache only', 'CloudFront + API caching', 'No caching needed', 'Database caching only'],
      correctAnswer: 1,
    },
    {
      id: 'e3',
      question: 'What is the best practice for handling sensitive data in Webiny?',
      type: 'multiple-choice' as const,
      options: ['Store in code', 'Use AWS Secrets Manager', 'Environment variables only', 'Database storage'],
      correctAnswer: 1,
    },
    {
      id: 'e4',
      question: 'How do you optimize GraphQL query performance?',
      type: 'multiple-choice' as const,
      options: ['Add more servers', 'Implement DataLoader, caching, and query optimization', 'Increase timeout', 'Use REST instead'],
      correctAnswer: 1,
    },
    {
      id: 'e5',
      question: 'What is the purpose of the Webiny Telemetry system?',
      type: 'multiple-choice' as const,
      options: ['User tracking', 'Performance monitoring and error tracking', 'Content analytics', 'SEO optimization'],
      correctAnswer: 1,
    },
    {
      id: 'e6',
      question: 'How should you handle database migrations in Webiny?',
      type: 'multiple-choice' as const,
      options: ['Manual scripts', 'Through plugins and lifecycle hooks', 'Not needed', 'Direct DynamoDB access'],
      correctAnswer: 1,
    },
    {
      id: 'e7',
      question: 'What is the recommended way to implement CI/CD for Webiny?',
      type: 'multiple-choice' as const,
      options: ['Manual deployment', 'GitHub Actions/GitLab CI with Webiny CLI', 'FTP uploads', 'AWS Console only'],
      correctAnswer: 1,
    },
    {
      id: 'e8',
      question: 'How do you implement custom authentication providers?',
      type: 'multiple-choice' as const,
      options: ['Modify core auth', 'Create security plugins', 'Not possible', 'Use third-party service only'],
      correctAnswer: 1,
    },
    {
      id: 'e9',
      question: 'What is the best approach for handling high-traffic scenarios?',
      type: 'multiple-choice' as const,
      options: ['Increase Lambda memory only', 'Implement caching, CDN, and optimize queries', 'Add more databases', 'Use EC2 instead'],
      correctAnswer: 1,
    },
    {
      id: 'e10',
      question: 'How should you structure a large-scale Webiny project?',
      type: 'multiple-choice' as const,
      options: ['Single package', 'Modular architecture with custom packages', 'Monorepo only', 'Separate repositories'],
      correctAnswer: 1,
    },
    {
      id: 'e11',
      question: 'What is the purpose of the Webiny Plugin system?',
      type: 'multiple-choice' as const,
      options: ['Just for themes', 'Extensibility and customization', 'Performance optimization', 'User management'],
      correctAnswer: 1,
    },
    {
      id: 'e12',
      question: 'How do you implement custom content model validations?',
      type: 'multiple-choice' as const,
      options: ['Client-side only', 'Through lifecycle hooks and plugins', 'Not supported', 'Database constraints'],
      correctAnswer: 1,
    },
    {
      id: 'e13',
      question: 'What is the recommended approach for multi-region deployment?',
      type: 'multiple-choice' as const,
      options: ['Single region only', 'Separate Webiny instances per region', 'Not supported', 'Manual replication'],
      correctAnswer: 1,
    },
    {
      id: 'e14',
      question: 'How should you implement custom API endpoints?',
      type: 'multiple-choice' as const,
      options: ['Separate Lambda functions', 'Through API Gateway plugins', 'Not possible', 'Modify core API'],
      correctAnswer: 1,
    },
    {
      id: 'e15',
      question: 'What is the best practice for error handling in Webiny?',
      type: 'multiple-choice' as const,
      options: ['Try-catch everywhere', 'Centralized error handling with proper logging', 'Ignore errors', 'Client-side only'],
      correctAnswer: 1,
    },
    {
      id: 'e16',
      question: 'How do you implement real-time features in Webiny?',
      type: 'multiple-choice' as const,
      options: ['Not possible', 'WebSockets via API Gateway', 'Polling only', 'Long polling'],
      correctAnswer: 1,
    },
    {
      id: 'e17',
      question: 'What is the recommended approach for backup and disaster recovery?',
      type: 'multiple-choice' as const,
      options: ['No backups needed', 'DynamoDB backups, S3 versioning, and infrastructure as code', 'Manual backups only', 'Database dumps'],
      correctAnswer: 1,
    },
    {
      id: 'e18',
      question: 'How should you implement content workflows in Webiny?',
      type: 'multiple-choice' as const,
      options: ['Manual process', 'Custom lifecycle hooks and approval systems', 'Not supported', 'Email-based'],
      correctAnswer: 1,
    },
    {
      id: 'e19',
      question: 'What is the best practice for monitoring Webiny applications?',
      type: 'multiple-choice' as const,
      options: ['No monitoring needed', 'CloudWatch, X-Ray, and custom metrics', 'Logs only', 'Third-party only'],
      correctAnswer: 1,
    },
    {
      id: 'e20',
      question: 'How do you optimize cold start times in Webiny?',
      type: 'multiple-choice' as const,
      options: ['Increase memory only', 'Provisioned concurrency, code optimization, and proper packaging', 'Not possible', 'Use containers'],
      correctAnswer: 1,
    },
  ],
}

