// This file is auto-generated by scripts/generate-mdx-registry.mjs
// Do not edit manually - run: npm run generate-mdx-registry

/**
 * Static import registry for all MDX lessons
 * Next.js requires explicit import statements for static analysis
 * This registry maps slugs to their import functions
 */
export const mdxImportRegistry: Record<string, () => Promise<any>> = {
  "foundation/about": () => import("@/content/lessons/foundation/about.mdx"),
  "foundation/infra-and-hosting": () => import("@/content/lessons/foundation/infra-and-hosting.mdx"),
  "foundation/multi-tenancy": () => import("@/content/lessons/foundation/multi-tenancy.mdx"),
  "foundation/webiny-apps": () => import("@/content/lessons/foundation/webiny-apps.mdx"),
  "foundation/webiny-framework": () => import("@/content/lessons/foundation/webiny-framework.mdx"),
  "foundation/webiny-parts": () => import("@/content/lessons/foundation/webiny-parts.mdx"),
  "getting-started/project-structure": () => import("@/content/lessons/getting-started/project-structure.mdx"),
  "getting-started/setup": () => import("@/content/lessons/getting-started/setup.mdx"),
  "getting-started/using-images": () => import("@/content/lessons/getting-started/using-images.mdx"),
}

/**
 * Get all registered lesson slugs
 */
export function getRegisteredSlugs(): string[] {
  return Object.keys(mdxImportRegistry)
}

export interface LessonRegistryItem {
  slug: string;
  import: () => Promise<any>;
  frontmatter: Record<string, any>;
  chapter: string;
}

/**
 * Full registry with lesson metadata
 * Includes frontmatter and chapter info for each lesson
 */
export const mdxRegistry: LessonRegistryItem[] = [
  {
    slug: "foundation/about",
    import: () => import("@/content/lessons/foundation/about.mdx"),
    frontmatter: {
          "title": "About Webiny",
          "description": "An introduction to Webiny and its core concepts.",
          "order": 1
    },
    chapter: "foundation"
  },
  {
    slug: "foundation/infra-and-hosting",
    import: () => import("@/content/lessons/foundation/infra-and-hosting.mdx"),
    frontmatter: {
          "title": "Infrastructure and Hosting",
          "description": "An overview of the infrastructure and hosting options for deploying Webiny applications.",
          "order": 5
    },
    chapter: "foundation"
  },
  {
    slug: "foundation/multi-tenancy",
    import: () => import("@/content/lessons/foundation/multi-tenancy.mdx"),
    frontmatter: {
          "title": "Multi-Tenancy",
          "description": "Understanding multi-tenancy in Webiny and how it enables managing multiple projects from a single instance.",
          "order": 6
    },
    chapter: "foundation"
  },
  {
    slug: "foundation/webiny-apps",
    import: () => import("@/content/lessons/foundation/webiny-apps.mdx"),
    frontmatter: {
          "title": "Webiny Applications",
          "description": "An overview of the built-in applications that are included with the Webiny content platform.",
          "order": 3
    },
    chapter: "foundation"
  },
  {
    slug: "foundation/webiny-framework",
    import: () => import("@/content/lessons/foundation/webiny-framework.mdx"),
    frontmatter: {
          "title": "Webiny Framework",
          "description": "An overview of the Webiny Framework, the underlying framework that powers the Webiny content platform.",
          "order": 4
    },
    chapter: "foundation"
  },
  {
    slug: "foundation/webiny-parts",
    import: () => import("@/content/lessons/foundation/webiny-parts.mdx"),
    frontmatter: {
          "title": "Parts that make Webiny",
          "description": "An overview of the core components that make the Webiny platform.",
          "order": 2
    },
    chapter: "foundation"
  },
  {
    slug: "getting-started/project-structure",
    import: () => import("@/content/lessons/getting-started/project-structure.mdx"),
    frontmatter: {
          "title": "Project Structure"
    },
    chapter: "getting-started"
  },
  {
    slug: "getting-started/setup",
    import: () => import("@/content/lessons/getting-started/setup.mdx"),
    frontmatter: {
          "title": "Setting Up Your Webiny Project"
    },
    chapter: "getting-started"
  },
  {
    slug: "getting-started/using-images",
    import: () => import("@/content/lessons/getting-started/using-images.mdx"),
    frontmatter: {
          "title": "Using Images in Lessons",
          "description": "Learn how to add images to your lesson content"
    },
    chapter: "getting-started"
  }
]

/**
 * Get all chapters with their lessons
 * Lessons are sorted by the 'order' field in frontmatter, or alphabetically by slug if no order is specified
 */
export function getChaptersWithLessons() {
  const chapters: Record<string, LessonRegistryItem[]> = {}
  mdxRegistry.forEach(item => {
    if (!chapters[item.chapter]) chapters[item.chapter] = []
    chapters[item.chapter].push(item)
  })
  
  // Sort lessons within each chapter by order field (if present) or by slug
  Object.keys(chapters).forEach(chapterKey => {
    chapters[chapterKey].sort((a, b) => {
      // If both have order, sort by order
      const orderA = a.frontmatter?.order ?? Number.MAX_SAFE_INTEGER
      const orderB = b.frontmatter?.order ?? Number.MAX_SAFE_INTEGER
      
      if (orderA !== orderB) {
        return orderA - orderB
      }
      
      // If order is the same (or both missing), sort alphabetically by slug
      return a.slug.localeCompare(b.slug)
    })
  })
  
  return chapters
}

/**
 * Get lesson by slug
 */
export function getLessonBySlug(slug: string): LessonRegistryItem | undefined {
  return mdxRegistry.find(item => item.slug === slug)
}
