// This file is auto-generated by scripts/generate-mdx-registry.mjs
// Do not edit manually - run: npm run generate-mdx-registry

/**
 * Static import registry for all MDX lessons
 * Next.js requires explicit import statements for static analysis
 * This registry maps slugs to their import functions
 */
export const mdxImportRegistry: Record<string, () => Promise<any>> = {
  "ai-agents-and-mcp-server/built-in-skills": () => import("@/content/lessons/ai-agents-and-mcp-server/built-in-skills.mdx"),
  "ai-agents-and-mcp-server/installing-the-mcp-server": () => import("@/content/lessons/ai-agents-and-mcp-server/installing-the-mcp-server.mdx"),
  "ai-agents-and-mcp-server/intro": () => import("@/content/lessons/ai-agents-and-mcp-server/intro.mdx"),
  "ai-agents-and-mcp-server/real-world-workflows": () => import("@/content/lessons/ai-agents-and-mcp-server/real-world-workflows.mdx"),
  "ai-agents-and-mcp-server/what-is-the-webiny-mcp-server": () => import("@/content/lessons/ai-agents-and-mcp-server/what-is-the-webiny-mcp-server.mdx"),
  "ai-agents-and-mcp-server/writing-custom-skills": () => import("@/content/lessons/ai-agents-and-mcp-server/writing-custom-skills.mdx"),
  "developing-with-webiny/ai-assisted-development": () => import("@/content/lessons/developing-with-webiny/ai-assisted-development.mdx"),
  "developing-with-webiny/debugging-errors-best-practices": () => import("@/content/lessons/developing-with-webiny/debugging-errors-best-practices.mdx"),
  "developing-with-webiny/extensions": () => import("@/content/lessons/developing-with-webiny/extensions.mdx"),
  "developing-with-webiny/intro": () => import("@/content/lessons/developing-with-webiny/intro.mdx"),
  "developing-with-webiny/local-development": () => import("@/content/lessons/developing-with-webiny/local-development.mdx"),
  "developing-with-webiny/project-folder-structure": () => import("@/content/lessons/developing-with-webiny/project-folder-structure.mdx"),
  "developing-with-webiny/webiny-sdk-overview": () => import("@/content/lessons/developing-with-webiny/webiny-sdk-overview.mdx"),
  "developing-with-webiny/whitelabel-extension": () => import("@/content/lessons/developing-with-webiny/whitelabel-extension.mdx"),
  "foundation/about": () => import("@/content/lessons/foundation/about.mdx"),
  "foundation/infra-and-hosting": () => import("@/content/lessons/foundation/infra-and-hosting.mdx"),
  "foundation/multi-tenancy": () => import("@/content/lessons/foundation/multi-tenancy.mdx"),
  "foundation/webiny-apps": () => import("@/content/lessons/foundation/webiny-apps.mdx"),
  "foundation/webiny-framework": () => import("@/content/lessons/foundation/webiny-framework.mdx"),
  "foundation/webiny-parts": () => import("@/content/lessons/foundation/webiny-parts.mdx"),
  "getting-started/deploy-webiny": () => import("@/content/lessons/getting-started/deploy-webiny.mdx"),
  "getting-started/installing-webiny": () => import("@/content/lessons/getting-started/installing-webiny.mdx"),
  "getting-started/webiny-cli-overview": () => import("@/content/lessons/getting-started/webiny-cli-overview.mdx"),
  "headless-cms/content-models-and-entries": () => import("@/content/lessons/headless-cms/content-models-and-entries.mdx"),
  "headless-cms/content-versioning": () => import("@/content/lessons/headless-cms/content-versioning.mdx"),
  "headless-cms/creating-content-model-via-code": () => import("@/content/lessons/headless-cms/creating-content-model-via-code.mdx"),
  "headless-cms/creating-content-model-via-ui": () => import("@/content/lessons/headless-cms/creating-content-model-via-ui.mdx"),
  "headless-cms/customize-data-list": () => import("@/content/lessons/headless-cms/customize-data-list.mdx"),
  "headless-cms/learn-webiny-nextjs-app": () => import("@/content/lessons/headless-cms/learn-webiny-nextjs-app.mdx"),
  "headless-cms/lifecycle-events": () => import("@/content/lessons/headless-cms/lifecycle-events.mdx"),
  "headless-cms/reading-data": () => import("@/content/lessons/headless-cms/reading-data.mdx"),
  "headless-cms/writing-data": () => import("@/content/lessons/headless-cms/writing-data.mdx"),
  "website-builder/article-listing-editor-component": () => import("@/content/lessons/website-builder/article-listing-editor-component.mdx"),
  "website-builder/editor-components": () => import("@/content/lessons/website-builder/editor-components.mdx"),
  "website-builder/setting-up-website-builder": () => import("@/content/lessons/website-builder/setting-up-website-builder.mdx"),
  "website-builder/theming-and-styling": () => import("@/content/lessons/website-builder/theming-and-styling.mdx"),
}

/**
 * Get all registered lesson slugs
 */
export function getRegisteredSlugs(): string[] {
  return Object.keys(mdxImportRegistry)
}

export interface LessonRegistryItem {
  slug: string;
  import: () => Promise<any>;
  frontmatter: Record<string, any>;
  chapter: string;
}

/**
 * Full registry with lesson metadata
 * Includes frontmatter and chapter info for each lesson
 */
export const mdxRegistry: LessonRegistryItem[] = [
  {
    slug: "ai-agents-and-mcp-server/built-in-skills",
    import: () => import("@/content/lessons/ai-agents-and-mcp-server/built-in-skills.mdx"),
    frontmatter: {
          "title": "Built-in Skills",
          "description": "A categorized tour of the skills that ship with the Webiny MCP server, so you know exactly what your AI agent already understands about Webiny.",
          "order": 3
    },
    chapter: "ai-agents-and-mcp-server"
  },
  {
    slug: "ai-agents-and-mcp-server/installing-the-mcp-server",
    import: () => import("@/content/lessons/ai-agents-and-mcp-server/installing-the-mcp-server.mdx"),
    frontmatter: {
          "title": "Installing the MCP Server",
          "description": "Connect the Webiny MCP server to your AI agent in one command, install the standalone package for use outside a Webiny project, or configure things manually for any agent.",
          "order": 2
    },
    chapter: "ai-agents-and-mcp-server"
  },
  {
    slug: "ai-agents-and-mcp-server/intro",
    import: () => import("@/content/lessons/ai-agents-and-mcp-server/intro.mdx"),
    frontmatter: {
          "title": "Building with AI Agents and Webiny MCP Server",
          "description": "An introduction to the AI-agent-driven way of building with Webiny — and why everything you learned in the previous chapters makes you good at it.",
          "order": 0
    },
    chapter: "ai-agents-and-mcp-server"
  },
  {
    slug: "ai-agents-and-mcp-server/real-world-workflows",
    import: () => import("@/content/lessons/ai-agents-and-mcp-server/real-world-workflows.mdx"),
    frontmatter: {
          "title": "Real-World Workflows",
          "description": "Three concrete workflows that put the Webiny MCP server to work — including the popular Figma-design-to-Website-Builder-component flow.",
          "order": 5
    },
    chapter: "ai-agents-and-mcp-server"
  },
  {
    slug: "ai-agents-and-mcp-server/what-is-the-webiny-mcp-server",
    import: () => import("@/content/lessons/ai-agents-and-mcp-server/what-is-the-webiny-mcp-server.mdx"),
    frontmatter: {
          "title": "What Is the Webiny MCP Server",
          "description": "Understand what the Model Context Protocol is, what the Webiny MCP server adds on top, and how skills give an AI agent expert knowledge about Webiny.",
          "order": 1
    },
    chapter: "ai-agents-and-mcp-server"
  },
  {
    slug: "ai-agents-and-mcp-server/writing-custom-skills",
    import: () => import("@/content/lessons/ai-agents-and-mcp-server/writing-custom-skills.mdx"),
    frontmatter: {
          "title": "Writing Your Own Skills",
          "description": "Author project-specific skills that teach the AI agent your domain models, internal APIs, and team conventions — and ship them in version control so every teammate benefits.",
          "order": 4
    },
    chapter: "ai-agents-and-mcp-server"
  },
  {
    slug: "developing-with-webiny/ai-assisted-development",
    import: () => import("@/content/lessons/developing-with-webiny/ai-assisted-development.mdx"),
    frontmatter: {
          "title": "AI-Assisted Development",
          "description": "How to use AI effectively when building extensions, integrations, and customizations on top of Webiny.",
          "order": 3
    },
    chapter: "developing-with-webiny"
  },
  {
    slug: "developing-with-webiny/debugging-errors-best-practices",
    import: () => import("@/content/lessons/developing-with-webiny/debugging-errors-best-practices.mdx"),
    frontmatter: {
          "title": "Debugging Errors & Best Practices",
          "description": "Learn how to effectively debug errors and follow best practices when developing with Webiny.",
          "order": 5
    },
    chapter: "developing-with-webiny"
  },
  {
    slug: "developing-with-webiny/extensions",
    import: () => import("@/content/lessons/developing-with-webiny/extensions.mdx"),
    frontmatter: {
          "title": "Extensions",
          "description": "Understanding Webiny extensions - what they are and how they work.",
          "order": 3
    },
    chapter: "developing-with-webiny"
  },
  {
    slug: "developing-with-webiny/intro",
    import: () => import("@/content/lessons/developing-with-webiny/intro.mdx"),
    frontmatter: {
          "title": "Developing with Webiny",
          "description": "An introduction to building, extending, testing, and debugging Webiny projects.",
          "order": 0
    },
    chapter: "developing-with-webiny"
  },
  {
    slug: "developing-with-webiny/local-development",
    import: () => import("@/content/lessons/developing-with-webiny/local-development.mdx"),
    frontmatter: {
          "title": "Local Development",
          "description": "How local development with Webiny works and best practices.",
          "order": 2
    },
    chapter: "developing-with-webiny"
  },
  {
    slug: "developing-with-webiny/project-folder-structure",
    import: () => import("@/content/lessons/developing-with-webiny/project-folder-structure.mdx"),
    frontmatter: {
          "title": "Project Folder Structure",
          "description": "Understanding the Webiny project folder structure and key files.",
          "order": 1
    },
    chapter: "developing-with-webiny"
  },
  {
    slug: "developing-with-webiny/webiny-sdk-overview",
    import: () => import("@/content/lessons/developing-with-webiny/webiny-sdk-overview.mdx"),
    frontmatter: {
          "title": "Webiny SDK",
          "description": "An overview of the Webiny SDK - what it is, what it covers, and how it fits into your development workflow.",
          "order": 6
    },
    chapter: "developing-with-webiny"
  },
  {
    slug: "developing-with-webiny/whitelabel-extension",
    import: () => import("@/content/lessons/developing-with-webiny/whitelabel-extension.mdx"),
    frontmatter: {
          "title": "White-Label Extension",
          "description": "Creating a white-label Admin extension to customize branding.",
          "order": 4
    },
    chapter: "developing-with-webiny"
  },
  {
    slug: "foundation/about",
    import: () => import("@/content/lessons/foundation/about.mdx"),
    frontmatter: {
          "title": "About Webiny",
          "description": "An introduction to Webiny and its core concepts.",
          "order": 1
    },
    chapter: "foundation"
  },
  {
    slug: "foundation/infra-and-hosting",
    import: () => import("@/content/lessons/foundation/infra-and-hosting.mdx"),
    frontmatter: {
          "title": "Infrastructure and Hosting",
          "description": "An overview of the infrastructure and hosting options for deploying Webiny applications.",
          "order": 5
    },
    chapter: "foundation"
  },
  {
    slug: "foundation/multi-tenancy",
    import: () => import("@/content/lessons/foundation/multi-tenancy.mdx"),
    frontmatter: {
          "title": "Multi-Tenancy",
          "description": "Understanding multi-tenancy in Webiny and how it enables managing multiple projects from a single instance.",
          "order": 6
    },
    chapter: "foundation"
  },
  {
    slug: "foundation/webiny-apps",
    import: () => import("@/content/lessons/foundation/webiny-apps.mdx"),
    frontmatter: {
          "title": "Webiny Applications",
          "description": "An overview of the built-in applications that are included with the Webiny content platform.",
          "order": 3
    },
    chapter: "foundation"
  },
  {
    slug: "foundation/webiny-framework",
    import: () => import("@/content/lessons/foundation/webiny-framework.mdx"),
    frontmatter: {
          "title": "Webiny Framework",
          "description": "An overview of the Webiny Framework, the underlying framework that powers the Webiny content platform.",
          "order": 4
    },
    chapter: "foundation"
  },
  {
    slug: "foundation/webiny-parts",
    import: () => import("@/content/lessons/foundation/webiny-parts.mdx"),
    frontmatter: {
          "title": "Parts that make Webiny",
          "description": "An overview of the core components that make the Webiny platform.",
          "order": 2
    },
    chapter: "foundation"
  },
  {
    slug: "getting-started/deploy-webiny",
    import: () => import("@/content/lessons/getting-started/deploy-webiny.mdx"),
    frontmatter: {
          "title": "Deploy Webiny",
          "description": "Guide to deploying Webiny to AWS and accessing the admin panel.",
          "order": 5
    },
    chapter: "getting-started"
  },
  {
    slug: "getting-started/installing-webiny",
    import: () => import("@/content/lessons/getting-started/installing-webiny.mdx"),
    frontmatter: {
          "title": "Installing Webiny",
          "description": "Step-by-step guide to installing Webiny on your local machine.",
          "order": 1
    },
    chapter: "getting-started"
  },
  {
    slug: "getting-started/webiny-cli-overview",
    import: () => import("@/content/lessons/getting-started/webiny-cli-overview.mdx"),
    frontmatter: {
          "title": "Webiny CLI Overview",
          "description": "An introduction to the Webiny Command Line Interface (CLI) and its functionalities.",
          "order": 2
    },
    chapter: "getting-started"
  },
  {
    slug: "headless-cms/content-models-and-entries",
    import: () => import("@/content/lessons/headless-cms/content-models-and-entries.mdx"),
    frontmatter: {
          "title": "Content Models and Content Entries",
          "description": "Understanding the foundation of Webiny Headless CMS - content models and entries.",
          "order": 1
    },
    chapter: "headless-cms"
  },
  {
    slug: "headless-cms/content-versioning",
    import: () => import("@/content/lessons/headless-cms/content-versioning.mdx"),
    frontmatter: {
          "title": "Content Versioning",
          "description": "Understanding how content versioning works in Webiny Headless CMS.",
          "order": 2
    },
    chapter: "headless-cms"
  },
  {
    slug: "headless-cms/creating-content-model-via-code",
    import: () => import("@/content/lessons/headless-cms/creating-content-model-via-code.mdx"),
    frontmatter: {
          "title": "Creating a Content Model via Code",
          "description": "Learn how to create content models programmatically and link them using reference fields.",
          "order": 4
    },
    chapter: "headless-cms"
  },
  {
    slug: "headless-cms/creating-content-model-via-ui",
    import: () => import("@/content/lessons/headless-cms/creating-content-model-via-ui.mdx"),
    frontmatter: {
          "title": "Creating a Content Model via UI",
          "description": "Learn how to create a Product content model through the Webiny Admin UI.",
          "order": 3
    },
    chapter: "headless-cms"
  },
  {
    slug: "headless-cms/customize-data-list",
    import: () => import("@/content/lessons/headless-cms/customize-data-list.mdx"),
    frontmatter: {
          "title": "Customize Data List",
          "description": "Learn how to customize the Headless CMS data list by adding custom columns to display important information at a glance.",
          "order": 9
    },
    chapter: "headless-cms"
  },
  {
    slug: "headless-cms/learn-webiny-nextjs-app",
    import: () => import("@/content/lessons/headless-cms/learn-webiny-nextjs-app.mdx"),
    frontmatter: {
          "title": "Learn Webiny Next.js App",
          "description": "Checkout the Learn Webiny Next.js App, create an API key and connect the app to Webiny API.",
          "order": 5
    },
    chapter: "headless-cms"
  },
  {
    slug: "headless-cms/lifecycle-events",
    import: () => import("@/content/lessons/headless-cms/lifecycle-events.mdx"),
    frontmatter: {
          "title": "Lifecycle Events",
          "description": "Create an extension that triggers before the contact us data is written. It verifies if the provided email address is work email or personal and sets a flag into the contact us content entry.",
          "order": 8
    },
    chapter: "headless-cms"
  },
  {
    slug: "headless-cms/reading-data",
    import: () => import("@/content/lessons/headless-cms/reading-data.mdx"),
    frontmatter: {
          "title": "Reading Data",
          "description": "Fetch and display products from Webiny Headless CMS using the Webiny SDK and Static Site Generation in Next.js.",
          "order": 6
    },
    chapter: "headless-cms"
  },
  {
    slug: "headless-cms/writing-data",
    import: () => import("@/content/lessons/headless-cms/writing-data.mdx"),
    frontmatter: {
          "title": "Writing Data",
          "description": "Create a contact form that submits data to Webiny Headless CMS using the Webiny SDK and the Manage API.",
          "order": 7
    },
    chapter: "headless-cms"
  },
  {
    slug: "website-builder/article-listing-editor-component",
    import: () => import("@/content/lessons/website-builder/article-listing-editor-component.mdx"),
    frontmatter: {
          "title": "Product Listing Editor Component",
          "description": "Build a custom Website Builder component that fetches products from Webiny Headless CMS and renders them inside a Website Builder page.",
          "order": 4
    },
    chapter: "website-builder"
  },
  {
    slug: "website-builder/editor-components",
    import: () => import("@/content/lessons/website-builder/editor-components.mdx"),
    frontmatter: {
          "title": "Editor Components",
          "description": "Learn what editor components are, how they work, and how to register custom ones through code.",
          "order": 2
    },
    chapter: "website-builder"
  },
  {
    slug: "website-builder/setting-up-website-builder",
    import: () => import("@/content/lessons/website-builder/setting-up-website-builder.mdx"),
    frontmatter: {
          "title": "Setting up Website Builder",
          "description": "Understand how the Website Builder connects to your frontend app, then get the starter kit running and create your first page.",
          "order": 1
    },
    chapter: "website-builder"
  },
  {
    slug: "website-builder/theming-and-styling",
    import: () => import("@/content/lessons/website-builder/theming-and-styling.mdx"),
    frontmatter: {
          "title": "Theming and Styling",
          "description": "Learn how the Website Builder theme works, how it's registered, and how mobile-responsive styling is applied.",
          "order": 3
    },
    chapter: "website-builder"
  }
]

/**
 * Get all chapters with their lessons
 * Lessons are sorted by the 'order' field in frontmatter, or alphabetically by slug if no order is specified
 */
export function getChaptersWithLessons() {
  const chapters: Record<string, LessonRegistryItem[]> = {}
  mdxRegistry.forEach(item => {
    if (!chapters[item.chapter]) chapters[item.chapter] = []
    chapters[item.chapter].push(item)
  })
  
  // Sort lessons within each chapter by order field (if present) or by slug
  Object.keys(chapters).forEach(chapterKey => {
    chapters[chapterKey].sort((a, b) => {
      // If both have order, sort by order
      const orderA = a.frontmatter?.order ?? Number.MAX_SAFE_INTEGER
      const orderB = b.frontmatter?.order ?? Number.MAX_SAFE_INTEGER
      
      if (orderA !== orderB) {
        return orderA - orderB
      }
      
      // If order is the same (or both missing), sort alphabetically by slug
      return a.slug.localeCompare(b.slug)
    })
  })
  
  return chapters
}

/**
 * Get lesson by slug
 */
export function getLessonBySlug(slug: string): LessonRegistryItem | undefined {
  return mdxRegistry.find(item => item.slug === slug)
}
